### ISSUE TITLE
E28. Implement static Figma design in Vue as single-page with toggle between front-page and result-page

### ISSUE THREAD

**Issue by regineru** [Kundestyrt-ReiseNavet/integration-tool-frontend#5]
Depends on #1 .
Implement the Figma-design in Vue, and add a temporary button somewhere to flip between the front-page and the result page.

The design should not have any functionality, just be a place-holder before we implement the functionality in other issues.

(This checklist was compiled from the drawn design, not from the Figma design.)
- [x] Header-section (top bar and info)
- [x] Alignment form
  - [x] Source file uploader placeholder
  - [x] Target file uploader placeholder
  - [x] Semantic relation picker
  - [x] "Compute alignment"-button
- [x] Result page
  - [x] "New alignment"-button (back-button)
  - [x] Result-header section
  - [x] Table containing placeholder table (just make up e.g. 3-5 rows of fake data)
  - [x] Download-button
- [x] Temporary button (not in Figma-design) to switch between the screens.

**Comment by sebastianvitterso** [comment]
@asnestige How is this coming along? Mind checking the checkboxes, and if it's done or should be reviewed - move it to that column?

**Comment by sebastianvitterso** [comment]
> @asnestige How is this coming along? Mind checking the checkboxes, and if it's done or should be reviewed - move it to that column?

I apologize, I thought this was the "design in Figma"-task that you were done with 😅
